spring.application.name=gestion_ferme
spring.datasource.url=jdbc:postgresql://localhost:5432/gest_ferme
spring.datasource.username=postgres
spring.datasource.password=mich
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true